services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:master
    container_name: couchdb-obsidian-livesync
    restart: always
    environment:
      SERVER_URL: ${SERVER_URL}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DATABASE: ${COUCHDB_DATABASE}
    ports:
      - "5984:5984"
    volumes:
      - ${COUCHDB_DATA}:/opt/couchdb/data
    networks:
      - caddy-network

  caddy:
    image: docker.io/caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_DATA}:/data
      - ${CADDY_CONFIG}:/config
    networks:
      - caddy-network


  watchtower:
    image: containrrr/watchtower
    container_name: Watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30


networks:
  caddy-network:
    external: true